### ISSUE TITLE
32 bit support

### ISSUE THREAD

**Issue by hypeq** [pytgcalls/ntgcalls#23]
needs a 32 bit support for most compatibility

**Comment by KSKOP69** [comment]
@hypeq 32 bit android ?

**Comment by hypeq** [comment]
> @hypeq 32 bit android ?

i have 32bit vps with debian and cant build module

**Comment by KSKOP69** [comment]
@hypeq get 64bit vps

**Comment by Laky-64** [comment]
32-bit platforms are no longer supported by any OS, so we will not be adding 32-bit support
