### ISSUE TITLE
Outdated build command in README

### ISSUE THREAD

**Issue by kolay-v** [pytgcalls/ntgcalls#29]
While docs have right one (https://pytgcalls.github.io/NTgCalls/Build%20Guide#Compilation), README.md build instructions for C doesn't work (https://github.com/pytgcalls/ntgcalls?tab=readme-ov-file#c-bindings).
Error is
```
python setup.py build_shared
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'build_shared'
```

**Comment by Laky-64** [comment]
Fixed
