### ISSUE TITLE
Will this dll library work for other languages?

### ISSUE THREAD

**Issue by Eriter555** [pytgcalls/ntgcalls#5]
Will this dll library work for other languages? What should I do after calling createCall in tdLib?

**Comment by Laky-64** [comment]
Yes, it works with any language, also here’s how connecting to a group call works:

https://github.com/pytgcalls/ntgcalls/blob/master/examples/python/shell_reader.py

**Comment by Eriter555** [comment]
> Yes, it works with any language, also here’s how connecting to a group call works:
> 
> https://github.com/pytgcalls/ntgcalls/blob/master/examples/python/shell_reader.py

Can it be used for calls in private chats or only for group calls? Thank you for your answers.

**Comment by rojvv** [comment]
Only group calls.

**Comment by Eriter555** [comment]
Maybe it makes sense to add a communication option for all types of calls? It would be convenient to have a dll and a wrapper to it and a couple of examples of its use in C or C++.

**Comment by Laky-64** [comment]
Regarding “all kinds of calls” we will add support later, for now it is not yet planned, while the examples on how to use it in c++ are not yet actually there, but we are working on intuitive documentation to guide users through the implementation of the library in other languages, so for now the most you can do is by reading how we did the example in golang
