### ISSUE TITLE
segmentation fault 

### ISSUE THREAD

**Issue by Jaykef** [pytgcalls/ntgcalls#8]
Code runs well then suddenly stops:

PyTgCalls v1.0.5 powered by NTgCalls v1.0.0.dev24, Copyright (C) 2021-2023 Laky-64 <https://github.com/Laky-64>
Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)

zsh: segmentation fault  python3 video.py

**Comment by Laky-64** [comment]
Can you share more details? Like if is reproducible and etc

**Comment by Jaykef** [comment]
> Can you share more details? Like if is reproducible and etc

Yes I was just trying out example/simple_calls/example_simple.py
with pyrogram client (got a connection)
but when I enter "!play" command in the group chat, it crashes:
<img width="546" alt="error" src="https://github.com/pytgcalls/pytgcalls/assets/11355002/853b50f2-25a5-457c-9688-68e997474f6c">

**Comment by Laky-64** [comment]
It happens always or happened just one time?

**Comment by Jaykef** [comment]
> It happens always or happened just one time?

always, I've tried many times, same result

**Comment by Laky-64** [comment]
Can you send here a video please? And when happens? Like when changing stream or etc

**Comment by Jaykef** [comment]
> Can you send here a video please? And when happens? Like when changing stream or etc

It happens for all commands and for examples that directly stream audio contents as well. Just try it.

**Comment by Laky-64** [comment]
Can you try at fly with pytgcalls 1.0.6?

**Comment by Jaykef** [comment]
okay

**Comment by Jaykef** [comment]
Gave this error when call command is used 

<img width="744" alt="Screenshot 2023-12-11 at 11 24 02" src="https://github.com/pytgcalls/ntgcalls/assets/11355002/a6aec1e2-2cc9-430a-9620-b2ce54bd44b0">

**Comment by Jaykef** [comment]
> Can you try at fly with pytgcalls 1.0.6?

Gave this error when call command is used 

<img width="744" alt="Screenshot 2023-12-11 at 11 24 02" src="https://github.com/pytgcalls/ntgcalls/assets/11355002/a6aec1e2-2cc9-430a-9620-b2ce54bd44b0">

**Comment by Laky-64** [comment]
You need to use an userbot, you can't use a bot to join in a group call

**Comment by Jaykef** [comment]
sorry but I don't get it, what's the difference between the userbot and bot and how do i create a userbot?

**Comment by Laky-64** [comment]
Userbot = using a telegram account as a "bot", the bot is literally what you do as a Bot Father instead

**Comment by Jaykef** [comment]
okay how do I use telegram account as a bot, I'm new to telegram.

**Comment by Laky-64** [comment]
Read telegram documentation and pytgcalls documentation 

https://pytgcalls.github.io/

**Comment by Jaykef** [comment]
I have, does this mean when I'm prompted for phone or bot token I enter phone number instead?

**Comment by Laky-64** [comment]
@Jaykef Yes!

**Comment by Jaykef** [comment]
okay got it, thanks

**Comment by Laky-64** [comment]
Ok the I will close this issue as a completed and as "won't fix"
